language: node_js
node_js:
- "0.11"
env:
  matrix:
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=dart2js
    BROWSERS=ChromeNoSandbox,Firefox
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=dart2js
    BROWSERS=ChromeNoSandbox,Firefox
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=vm
    BROWSERS=DartiumWithWebPlatform
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=vm
    BROWSERS=DartiumWithWebPlatform
  global:
  - FIREFOX_VERSION="29.0"
  - CHROME_BIN=/usr/bin/google-chrome
  - GITHUB_TOKEN_ANGULAR_ORG=a6a7d3030705da732ce9aca16b03bc02ec8d674c

# Don't test these branches.
branches:
  except:
    - g3v1x

before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install.sh
before_script:
- ./scripts/travis/rebase.sh
- ./scripts/travis/setup.sh
script:
- ./scripts/travis/build.sh
after_success:
- ./scripts/travis/after-success.sh
